# Generated by Django 3.0.7 on 2020-10-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('Latitude', models.FloatField(help_text='Latitude')),
                ('Longitude', models.FloatField(help_text='Longitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=255, primary_key=True, serialize=False)),
                ('Shift', models.CharField(help_text='Shift', max_length=100)),
                ('Date', models.DateField(help_text='Date')),
                ('Age', models.CharField(help_text='Age', max_length=255)),
                ('Primary_Fur_Color', models.CharField(help_text='Primary Fur Color', max_length=255)),
                ('Location', models.CharField(help_text='Location', max_length=255)),
                ('Specific_Location', models.CharField(help_text='Specific Location', max_length=255)),
                ('Running', models.BooleanField(help_text='Running')),
                ('Chasing', models.BooleanField(help_text='Chasing')),
                ('Climbing', models.BooleanField(help_text='Climbing')),
                ('Eating', models.BooleanField(help_text='Eating')),
                ('Foraging', models.BooleanField(help_text='Foraging')),
                ('Other_Activities', models.CharField(help_text='Other Activities', max_length=255)),
                ('Kuks', models.BooleanField(help_text='Kuks')),
                ('Quaas', models.BooleanField(help_text='Quaas')),
                ('Moans', models.BooleanField(help_text='Moans')),
                ('Tail_flags', models.BooleanField(help_text='Tail flags')),
                ('Tail_twitches', models.BooleanField(help_text='Tail twitches')),
                ('Approaches', models.BooleanField(help_text='Approaches')),
                ('Indifferent', models.BooleanField(help_text='Indifferent')),
                ('Runs_from', models.BooleanField(help_text='Runs from')),
            ],
        ),
    ]
