# Generated by Django 3.0.7 on 2020-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20201013_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', 'Unknown')], help_text='Age', max_length=255, null=True),
        ),
    ]
